### ISSUE TITLE
GetAllProductQuerry Result problem

### ISSUE THREAD

**Issue by Mike6x** [aspnetcorehero/Boilerplate#1]
**Describe the bug**
When I try "GetAllProductQuerry" method, the result message " succeeded" always "Fail" in case Data is not null

**Screenshots**
![image](https://user-images.githubusercontent.com/25998007/102703907-bf37aa00-42a7-11eb-90ab-fc2ead1ca34a.png)

**Comment by iammukeshm** [comment]
Thanks for letting me know. There was an issue with the package. It's fixed now in the latest repository! cheers
