### ISSUE TITLE
Connection Already Exist

### ISSUE THREAD

**Issue by webzest** [aspnetcorehero/Boilerplate#25]
**Describe the bug**
InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.

**To Reproduce**
Generated a new application with dotnet.
Upgraded to the latest Nuget packages.
Conducted the Migrations to create the new database on my  local MSSQL 2019 Server
Tested the Token API Successfully.
Selected the Web as default App and logged in with the default Super Admin User
1. Go to 'Admin Settings'
2. Click on 'Users'
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6105504/111876748-88406580-8976-11eb-8f1b-9ac31e8f5a46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Additional context**
Clicking on Roles worked, but the remaining links did not.  Same error was generated

**Comment by crnjakovic** [comment]
I reported same issue in #21 two weeks ago although in my case MS SQL worked, while MySQL and postgresql didn't. Same error, same thing regarding only Roles section working. If you find something out, let me know, as it doesn't look like we'll be getting help here :)

**Comment by iamshen** [comment]
in postgres
 
`Your.Web/Permission/PermissionAuthorizationHandler.cs`

`var userRoles = _roleManager.Roles.Where(x => userRoleNames.Contains(x.Name));`

change to

`var userRoles = _roleManager.Roles.Where(x => userRoleNames.Contains(x.Name)).ToList();`

**This is because do foreach over an EF Core LINQ query isn't supported**

**Comment by webzest** [comment]
Yes, that is the solution.  Thank You!

**Comment by thanhdongha** [comment]
thanks, it's worked for me
