### ISSUE TITLE
Interface name does not match the file name 

### ISSUE THREAD

**Issue by michelbergeron** [aspnetcorehero/Boilerplate#3]
Hi, I think there is a small issue: the names have been mixed up in the file:

AspNetCoreHero.Boilerplate.Application/Interfaces/CacheRepositories/I**Product**CacheRepository.cs

the interface name is "I**Brand**CacheRepository"  

The same thing occured in the file "IBrandCacheRepository.cs" 
Thanks!

**Comment by iammukeshm** [comment]
Thanks for spotting the issue 👍
